change_language:
  url:   /change_language
  param: 
    module: language
    action: changeLanguage

ftp_account:
  class: sfPropelRouteCollection
  options:
    model:               FtpAccount
    module:              ftp_account
    prefix_path:         ftp_account
    column:              id
    with_wildcard_routes: true
    prefix_path:          /:sf_culture/ftp_account
    requirements:         
      sf_culture:  (?:ti|en)
    
samba_account:
  class: sfPropelRouteCollection
  options:
    model:               SambaAccount
    module:              samba_account
    prefix_path:         samba_account
    column:              id
    with_wildcard_routes: true
    prefix_path:          /:sf_culture/samba_account
    requirements:         
      sf_culture:  (?:ti|en)
    
unix_account:
  class: sfPropelRouteCollection
  options:
    model:               UnixAccount
    module:              unix_account
    prefix_path:         unix_account
    column:              id
    with_wildcard_routes: true
    prefix_path:          /:sf_culture/unix_account
    requirements:         
      sf_culture:  (?:ti|en)

email_alias:
  class: sfPropelRouteCollection
  options:
    model:               EmailAlias
    module:              emailalias
    prefix_path:         emailalias
    column:              id
    with_wildcard_routes: true
    prefix_path:          /:sf_culture/email_alias    
    requirements:         
      sf_culture:  (?:ti|en)

user_identification:
  class: sfPropelRouteCollection
  options:
    model:               UserIdentification
    module:              useridentification
    prefix_path:         useridentification
    column:              id
    with_wildcard_routes: true
    prefix_path:          /:sf_culture/user_identification
    requirements:         
      sf_culture:  (?:ti|en)

user:
  class: sfPropelRouteCollection
  options:
    model:               User
    module:              user
    prefix_path:         user
    column:              id
    with_wildcard_routes: true
    prefix_path:          /user/:sf_culture
    requirements:         
      sf_culture:  (?:ti|en)

domainname:
  class: sfPropelRouteCollection
  options:
    model:               Domainname
    module:              domainname
    prefix_path:         domainname
    column:              id
    with_wildcard_routes: true
    prefix_path:          /:sf_culture/domainname
    requirements:         
      sf_culture:  (?:ti|en)

# default rules
localized_homepage:
  url:   /:sf_culture
  param: { module: default, action: index }
  requirements:
    sf_culture: (?:ti|en)

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
