propel:
  domains:
    id:           ~
    name:         { type: varchar(255), required: true, index: unique }

  users:
    id:           ~
    first_name:   { type: varchar(255), required: true }
    fathers_name: { type: varchar(255), required: true }
    gfathers_name:{ type: varchar(255), required: true }
    login_name:   { type: varchar(255), required: true, index: unique }
    phone:        { type: varchar(255) }
    nt_password:  { type: varchar(255), required: true }
    lm_password:  { type: varchar(255), required: true }
    crpt_password:{ type: varchar(255), required: true }
    unix_password:{ type: varchar(255), required: true }
    gid:          { type: integer, required: true }
    uid:          { type: integer, required: true, index: unique }
    status:       { type: integer, required: true, default: 1 }
    alt_email:    { type: varchar(255), required: true }
    expires_at:   { type: timestamp, required: true }
    created_at:   ~
    updated_at:   ~
    uni_id:       { type: integer, foreignTable: uni_ids, foreignReference: id, required: true, primaryKey: true, onDelete: cascade}
    privilege_id: { type: integer, foreignTable: privilege, foreignReference: id, required: true }
    domain_id:    { type: integer, foreignTable: domains, foreignReference: id, required: true }
    
  email_accounts:
    id:           ~
    local_part:   { type: varchar(255), required: true }
    quota:        { type: varchar(32), required: true default: '500000S'}
    updated_at:   ~
    uni_id:       { type: integer, foreignTable: uni_ids, foreignReference: id, required: true, primaryKey: true }
  
  privilege:
    id:           ~
    type:         { type: varchar(255), required: true }
    
  uni_ids:
    id:           ~
    type:         { type: varchar(255), required: true }

