propel:
  domain:
    id:           ~
    name:         { type: varchar(255), required: true, index: unique }

  user:
    id:           ~
    first_name:   { type: varchar(255), required: true, minlength: 2}
    fathers_name: { type: varchar(255), required: true, minlength: 2}
    gfathers_name:{ type: varchar(255), required: true, minlength: 2}
    login:        { type: varchar(255), required: true, index: unique }
    phone:        { type: varchar(255) }
    nt_password:  { type: varchar(255), required: true }
    lm_password:  { type: varchar(255), required: true }
    crypt_password:
                  { type: varchar(255), required: true }
    unix_password:{ type: varchar(255), required: true }
    gid:          { type: integer, required: true }
    uid:          { type: integer, required: true, index: unique }
    status:       { type: integer, required: true, default: 1 }
    alt_email:    { type: varchar(255), required: true email: true}
    home_directory: 
                  { type: varchar(255), required: true }
    expires_at:   { type: timestamp, required: true }
    created_at:   ~
    updated_at:   ~
    university_id:{ type: integer, foreignTable: university_id, foreignReference: id, required: true, primaryKey: true, onDelete: cascade}
    domain_id:    { type: integer, foreignTable: domain, foreignReference: id, required: true }
    
  email_account:
    id:           ~
    local_part:   { type: varchar(255), required: true }
    quota:        { type: varchar(32), required: true default: '500000S' }
    updated_at:   ~
    university_id:{ type: integer, foreignTable: university_id, foreignReference: id, required: true, primaryKey: true }
    
    
    _uniques:     { unique_index1: [local_part, domain_name] }

 
  university_id:
    id:           ~
    type:         { type: varchar(255), required: true }

  unix_account:
    id:           ~
    user_id:      { type: varchar(255), foreignTable: users, foreignReference: id,required: true} #unique together with user ID
    host_name:    { type: varchar(255), required: true} #unique together with user ID
    quota:        { type: integer }
    ts_update:    ~
    _uniques:     {unix_uniques:[user_id, host_name}

  proxy_account:        
    id:           ~
    user_id:      { type: varchar(255), foreignTable: users, foreignReference: id, required: true, index: unique }

  ftp_account:
    id:           ~
<<<<<<< HEAD:schema.yml
    user_id:      { type: varchar(255), foreignTable: users, foreignReference: id, required: true}
    domain_id:     { type: varchar(255), foreignTable: domains, foreignReference: id, required: true}
=======
    user_id:       { type: varchar(255), required: true}
    domain_id:     { type: varchar(255), required: true}
>>>>>>> 84eb81fb1c07331dd9efb07e37e9e6c32f551951:schema.yml
    up_bandwidth:  { type: integer }
    dl_bandwidth:  { type: integer }
    ip_access:     { }
    quota:         { type: integer}
    qutoa_file:    { type: integer}
    ts_update:     ~

  samba_account:
    id:           ~
<<<<<<< HEAD:schema.yml
    user_id:      { type: varchar(255), foreignTable: users, foreignReference: id, required: true }
    acount_flag:   { type: varchar(255), required: true }
=======
    user_id:      { type: varchar(255), required: true }
    acount_flag:  { type: varchar(255), required: true }
>>>>>>> 84eb81fb1c07331dd9efb07e37e9e6c32f551951:schema.yml
    host_name:    { type: varchar(255), required: true }
    ts_update:    ~
    _uniques:     {samba_uniques:[user_id, host_name}

  email_alias:
    id:           ~
    localpart:    { type: varchar(255), required: true }
    destination:  { type: varchar(255), required: true }
    ts_update:     ~
