generator:
  class: sfPropelGenerator
  param:
    model_class:           FtpAccount
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          ftp_account
    with_propel_route:     1

    config:
      actions: ~
      fields:  
        user_id: 
          label: User
        up_bandwidth:
           label: Upload bandwidth
           help: 0 is unlimited upload band width(KB)
        down_bandwidth:
           label: Down BW
      list:
        actions: {}    
            label: Download bandwidth
            help: 0 is unlimited download band width.(KB)
        quota_size:
             label: Quota size
             help: 0 is unlimited quota size.
        quota_files:
                label: Number of quota files
                help: 0 is unlimited quota files.

      list:    
        title: University Ftp Account
        display: [user_fullname, up_bandwidth, down_bandwidth]
      filter:  
        display: [user_id, up_bandwidth, down_bandwidth, ip_access, quota_size, quota_files]
      form:    ~
      edit:    
        title: Edit FTP Account
        display: [user_id, up_bandwidth, down_bandwidth, ip_access, quota_size, quota_files]  
        fields:
      new:     
        title: Add FTP account
        display: [user_id, up_bandwidth, down_bandwidth, ip_access, quota_size, quota_files]
