default:
    is_secure: on
    
edit:
    is_secure: on
    credentials: [[sysadmin, admin]]
    
delete:
    is_secure: on
    credentials: [[sysadmin, admin]]
new:
    is_secure: on
    credentials: [[sysadmin,admin]]    
