propel:
  domain:
    id:           ~
    name:         { type: varchar(255), required: true, index: unique }

  user:
    id:           ~
    first_name:   { type: varchar(255), required: true, minlength: 3}
    fathers_name: { type: varchar(255), required: true, minlength: 3}
    grand_fathers_name:
                  { type: varchar(255), required: true, minlength: 3}
    login:        { type: varchar(255), required: true, index: unique }
    phone:        { type: varchar(255)}
    nt_password:  { type: varchar(255), required: true }
    lm_password:  { type: varchar(255), required: true }
    crypt_password:
                  { type: varchar(255), required: true }
    unix_password:{ type: varchar(255), required: true }
    gid:          { type: integer, required: true }
    uid:          { type: integer, required: true, index: unique }
    status:       { type: integer, required: true, default: 0 }
    alt_email:    { type: varchar(255), required: true email: true}
    home_directory: 
                  { type: varchar(255), required: true }
    expires_at:   { type: timestamp, required: true }
    created_at:   ~
    updated_at:   ~
    university_id:{ type: integer, foreignTable: university_id, foreignReference: id, required: true, onDelete: cascade}
    domain_id:    { type: integer, foreignTable: domain, foreignReference: id, required: true }
    
  email_account:
    id:           ~
    
    quota:        { type: varchar(32), required: true default: '500000S' }
    updated_at:   ~
    university_id:{ type: integer, foreignTable: university_id, foreignReference: id, required: true }
    domain_id:  { type: integer, foreignTable: domain, foreignReference: id, required: true } 
    _uniques:     { unique_index01: [local_part, domain_id] }
  
  university_id:
    id:           { type: varchar(255), required: true, primaryKey: true }
    type:         { type: varchar(255), required: true }

  unix_account:
    id:           ~
    user_id:      { type: integer, foreignTable: user, foreignReference: id, required: true } 
    host_name:    { type: varchar(255), required: true}
    quota:        { type: varchar(32), required: true default: '500000S' }
    ts_update:    ~
    _uniques:     { unique_index02: [user_id, host_name] }

  proxy_account:
    id:           ~
    user_id:      { type: integer, foreignTable: user, foreignReference: id, required: true } 

  ftp_account:
    id:           ~
    user_id:      { type: integer, foreignTable: user, foreignReference: id, required: true } 
    domain_id:    { type: varchar(255), foreignTable: domain, foreignReference: id, required: true}
    up_bandwidth: { type: integer, required: true default: '500000S' }
    dl_bandwidth: { type: integer, required: true default: '500000S' }
    ip_access:    { type: varchar(255), required: true  }
    quota:        { required: true default: '500000S'}
    qutoa_file:   { type: varchar(255), required: true default: 10 }
    ts_update:    ~

  samba_account:
    id:           ~
    user_id:      { type: integer, foreignTable: user, foreignReference: id, required: true }
    acount_flag:  { type: varchar(255), required: true }
    host_name:    { type: varchar(255), required: true }
    ts_update:    ~
    _uniques:     { unique_index03: [user_id, host_name] }

  email_alias:
    id:           ~
    user_id:      { type: integer, foreignTable: user, foreignReference: id, required: true }
    local_part:   { type: varchar(255), foreignTable: user, foreignReference: local_part, required: true }
    destination:  { type: varchar(255), required: true, email: true}
    ts_update:     ~
