generator:
  class: sfPropelGenerator
  param:
    model_class:           User
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          user
    with_propel_route:     1

    config:
      actions: ~
      fields:  ~
      list:
        object_actions:
            _edit: ~
            _delete: ~
            toggle_status : ~
        batch_actions:
             _delete: ~
             toggle_status : ~
        display: [login, full_name, status, expires_at]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
