default:
    is_secure: off
    
edit:
    is_secure: on
    credentials: [[secretary, admin]]
    
delete:
    is_secure: on
    credentials: admin
new:
    is_secure: on
    credentials: [[secretary,admin]]    
